---
abstract: 'Attempt to recover from people calling UNIVERSAL::isa as a function'
author:
  - chromatic
build_requires:
  CGI: 0
  Test::More: 0
  overload: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UNIVERSAL-isa
requires:
  Scalar::Util: 0
  UNIVERSAL: 0
  perl: 5.6.2
  vars: 0
  warnings::register: 0
resources:
  homepage: https://github.com/chromatic/UNIVERSAL-isa
  repository: https://github.com/chromatic/UNIVERSAL-isa.git
version: 1.20110613
